# Generated by Django 2.0 on 2018-08-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=20)),
                ('ipaddress', models.CharField(max_length=15, unique=True)),
                ('hostname', models.CharField(max_length=100)),
                ('fqdn', models.CharField(max_length=100)),
                ('sshKey', models.CharField(max_length=1700)),
                ('server_user', models.CharField(max_length=20)),
            ],
        ),
    ]
